### ISSUE TITLE
I am getting a Value Error in the conver_to_eager_tensor class

### ISSUE THREAD

**Issue by constant5** [Goldesel23/Temporal-Ensembling-for-Semi-Supervised-Learning#4] opened 2018-11-08 23:27 UTC
Whenever I try to execute train_pi_model.py or train_temporal_model.py I get this same error.  Can someone help me diagnose the problem?

`(tf-env) C:\Users\crm0376\Documents\ONR\Temporal-Ensembling-for-Semi-Supervised-Learning-master>C:/Users/crm0376/.local/conda_root/envs/tf-env/python.exe c:/Users/crm0376/Documents/ONR/Temporal-Ensembling-for-Semi-Supervised-Learning-master/train_temporal_ensembling_model.py
2018-11-08 17:23:21.615533: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "c:/Users/crm0376/Documents/ONR/Temporal-Ensembling-for-Semi-Supervised-Learning-master/train_temporal_ensembling_model.py", line 199, in <module>
    main()
  File "c:/Users/crm0376/Documents/ONR/Temporal-Ensembling-for-Semi-Supervised-Learning-master/train_temporal_ensembling_model.py", line 111, in main
    model, unsupervised_weight, current_ensemble_targets)
  File "c:\Users\crm0376\Documents\ONR\Temporal-Ensembling-for-Semi-Supervised-Learning-master\pi_model.py", line 54, in temporal_ensembling_gradients
    model, unsupervised_weight, ensembling_targets)
  File "c:\Users\crm0376\Documents\ONR\Temporal-Ensembling-for-Semi-Supervised-Learning-master\pi_model.py", line 25, in temporal_ensembling_loss
    z_labeled = model(X_train_labeled)
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "c:\Users\crm0376\Documents\ONR\Temporal-Ensembling-for-Semi-Supervised-Learning-master\pi_model.py", line 264, in call
    h = self.__apply_image_augmentation(h)
  File "c:\Users\crm0376\Documents\ONR\Temporal-Ensembling-for-Semi-Supervised-Learning-master\pi_model.py", line 248, in __apply_image_augmentation
    image, random_translation.numpy, 'NEAREST')
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\contrib\image\python\ops\image_ops.py", line 125, in translate
    translations_to_projective_transforms(translations),
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\contrib\image\python\ops\image_ops.py", line 191, in translations_to_projective_transforms
    translations, name="translations", dtype=dtypes.float32)
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\python\framework\ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\python\framework\constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\python\framework\constant_op.py", line 179, in constant
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\crm0376\.local\conda_root\envs\tf-env\lib\site-packages\tensorflow\python\framework\constant_op.py", line 114, in convert_to_eager_tensor
    return ops.EagerTensor(value, context=handle, device=device, dtype=dtype)
ValueError: Attempt to convert a value (<bound method _EagerTensorBase.numpy of <tf.Tensor: id=233, shape=(1, 2), dtype=float32, numpy=array([[-0.76205397,  0.42147446]], dtype=float32)>>) with an unsupported type (<class 'method'>) to a Tensor.`

**Comment by tensorfreitas** [comment] 2018-11-08 23:37
Is this without changing the code.? Are you running a version of tensorflow more recent than 1.10?

**Comment by constant5** [comment] 2018-11-08 23:52
Yes I am running tensorflow 1.12 with no change to the code.  I will downgrade to 1.10 and try again.

**Comment by tensorfreitas** [comment] 2018-11-08 23:56
After upgrading to 1.12 or 1.11 I also go the error. I will investigate the
error as it seems to occur in the image augmentation phase


constant5 <notifications@github.com> escreveu em qui, 8/11/2018 às 23:52 :

**Comment by constant5** [comment] 2018-11-08 23:57
I downgraded to 1.10 but no help. Here are my environment dependencies. 

absl-py             0.5.0
astor               0.7.1
astroid             2.0.4
backcall            0.1.0
certifi             2018.10.15
colorama            0.4.0
decorator           4.3.0
gast                0.2.0
grpcio              1.15.0
h5py                2.8.0
ipykernel           5.1.0
ipython             7.1.1
ipython-genutils    0.2.0
isort               4.3.4
jedi                0.13.1
jupyter-client      5.2.3
jupyter-core        4.4.0
Keras               2.2.4
Keras-Applications  1.0.6
Keras-Preprocessing 1.0.5
lazy-object-proxy   1.3.1
Markdown            2.6.11
mccabe              0.6.1
numpy               1.14.5
pandas              0.23.4
parso               0.3.1
pickleshare         0.7.5
pip                 18.1
prompt-toolkit      2.0.7
protobuf            3.6.1
Pygments            2.2.0
pylint              2.1.1
python-dateutil     2.7.3
pytz                2018.5
PyYAML              3.13
pyzmq               17.1.2
scipy               1.1.0
setuptools          39.1.0
six                 1.11.0
tensorboard         1.10.0
tensorflow          1.10.0
termcolor           1.1.0
tornado             5.1.1
traitlets           4.3.2
typed-ast           1.1.0
wcwidth             0.1.7
Werkzeug            0.14.1
wheel               0.31.1
wincertstore        0.2
wrapt               1.10.11

**Comment by constant5** [comment] 2018-11-09 00:04
I commented out Image Augmentation and it is running so you are probably correct that it is problem with that module.

**Comment by tensorfreitas** [comment] 2018-11-09 09:53
I'll come back to you after resolving the issue. I wrote the code with tensorflow 1.8/1.9 so I guess after that something changed. I will investigate further this weekend.

**Comment by constant5** [comment] 2018-11-09 14:20
I think I fixed this by downgrading to tensorflow 1.9 AND modifying the call to  tf.contrib.image.translate(). 

`image = tf.contrib.image.translate(image, random_translation.numpy, 'NEAREST')`

to 

`image = tf.contrib.image.translate(image, random_translation, 'NEAREST')`

**Comment by tensorfreitas** [comment] 2018-11-09 16:55
Thanks for the effort. I still got other kind of error on most recent tensorflow release. I am currently not able to debug it on my company laptop but I will do it tomorrow!

**Comment by tensorfreitas** [comment] 2018-11-10 17:31
I think the issue is solved with my last commit. After new releases added the possibility of tf.contrib.image.transform to output images with different size of the input images it introduced this error. I changed the code to adress this problem. 

Thanks for the effort and for your help @constant5.

**Closed as completed by tensorfreitas** 2018-11-10 17:31 UTC

**Comment by constant5** [comment] 2018-11-10 21:33
Great. Seems to be working well with TF=1.11!!

**Comment by tensorfreitas** [comment] 2018-11-11 14:33
I think they are also working on it to get it solved : https://github.com/tensorflow/tensorflow/issues/23654
