### ISSUE TITLE
why epoch training time become more and more long

### ISSUE THREAD

**Issue by sanlb** [Goldesel23/Temporal-Ensembling-for-Semi-Supervised-Learning#2] opened 2018-10-11 07:07 UTC
then i find that the training time of this code 
current_outputs, loss_val, grads = temporal_ensembling_gradients(X_labeled_train, y_labeled_train, X_unlabeled_train,model, unsupervised_weight, current_ensemble_targets)
become more and more long after every epoch 
anyone know how to deal with this problem. thanks

**Comment by tensorfreitas** [comment] 2018-10-14 13:40
In theory temporal_ensemble_gradients should take the same amount of time across epochs. Are you sure is that function that is causing the increase of epoch time? How did you benchmark? 

Seems though related to #1 . May be something related to eager execution but I have to search for it online.

**Comment by sanlb** [comment] 2018-10-14 15:05
thank you for your reply, after doing some experiments, find that i have the same problem about #1, the gpu uti will become more and more low, even after several epochs, it wil become 0 and then get high (use nvidia-smi). because few message online about  eager execution, i cannot get a reasonable answer.

**Comment by tensorfreitas** [comment] 2018-10-15 06:49
After benchmarking I confirm this is a problem. I will try to investigate the source of the problem. The cause of the slowdown seems not to be in logging like I thought.

**Comment by tensorfreitas** [comment] 2018-10-16 12:08
I opened a issue in https://github.com/tensorflow/tensorflow/issues/23014 also realted to #1 . I will wait for the support. Thanks for pointing out!

**Comment by tensorfreitas** [comment] 2018-10-17 22:28
@sanlb I pushed a new model according to the suggested by (https://github.com/tensorflow/tensorflow/issues/23014)definition that should solve the problem. I will close the issue.

**Closed as completed by tensorfreitas** 2018-10-17 22:28 UTC

**Comment by sanlb** [comment] 2018-10-18 00:44
that is great, thanks for your help
